# -*- coding: utf-8 -*-
"""MIAAD Prope_Practica 01 Python Javier Rebull.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16U-dOO0o448bwRQ0_r6_IHaKAAMRGdt-

<div align="center">

🎓
# **Universidad Autónoma de Ciudad Juárez**
## **Maestría en Inteligencia Artificial y Analítica de Datos (MIAAD)**
<br><br>

---
<br>

# 💻 **Práctica 1: Tipos de Variables en Python** 🐍
<br>

### MÓDULO 2: Programación
<br>

---
<br>

🧑‍🏫 **Profesor Titular:** Dr. Luis Carlos Méndez González
<br><br>

---
<br>

🧑‍🎓 **Estudiante:**
## **Javier Augusto Rebull Saucedo**
Candidato a Entrar al Postgrado
<br><br>

</div>

---

<div align="right">
📚 Curso Propedéutico - MIAAD
<br>
📅 01 de junio de 2025
</div>



---

## Requisitos de Finalización

* **Abre:** viernes, 9 de mayo de 2025, 00:00
* **Vence:** domingo, 1 de junio de 2025, 23:58

---

## Descripción

Declara diferentes tipos de variables en Python y muestra su valor y tipo.

---

## Instrucciones:

1.  Crea las siguientes variables en Python:
    * Una variable **entera**.
    * Una variable de **punto flotante**.
    * Una variable de **texto** (cadena).
    * Una variable **booleana**.
2.  Utiliza la función `print()` para mostrar el **valor** y el **tipo** de cada variable.
3.  Envía tu código en un archivo `.py` y una **captura de pantalla** de los resultados obtenidos al ejecutar tu código.

---
"""

# Declaración de una variable entera
variable_entera = 10

# Declaración de una variable de punto flotante
variable_flotante = 25.75

# Declaración de una variable de texto (cadena)
variable_texto = "Hola, Python!"

# Declaración de una variable booleana
variable_booleana = False

# --- Variable Entera ---
print("--- Variable Entera ---")
print("Valor:", variable_entera)
print("Tipo:", type(variable_entera))
print()

# --- Variable de Punto Flotante ---
print("--- Variable de Punto Flotante ---")
print("Valor:", variable_flotante)
print("Tipo:", type(variable_flotante))
print()

# --- Variable de Texto (Cadena) ---
print("--- Variable de Texto (Cadena) ---")
print("Valor:", variable_texto)
print("Tipo:", type(variable_texto))
print()

# --- Variable Booleana ---
print("--- Variable Booleana ---")
print("Valor:", variable_booleana)
print("Tipo:", type(variable_booleana))
print()